### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by maxolasersquad** [TheSamsai/Castawesome#7]
I've actually got a branch I'm working on to make this happen, but I haven't pushed that branch to my local fork yet. I'm just opening up this issue so it can be discussed and/or tracked.

**Comment by TheSamsai** [comment]
One of the big issues with Python has been the divide between Python 2 and Python 3 and I like the idea of moving Castawesome to Python 3. That is, of course, if the necessary libraries are ready and most popular distros can access them relatively easily. Py3k itself is probably being shipped by default on all recent distributions, so that's no longer a concern. If you get all the GTK stuff and potential standard library changes handled, I'm happy to merge your branch.

**Comment by maxolasersquad** [comment]
Personal opinions aside, Python3 is the way forward. Python2 will not be around forever. I don't think there is a current distro out there shipping without Python3.

The port is going well, and libraries seem to just be there. It actually does load interface for a split second before crashing as it tries to load the configuration file.

**Comment by maxolasersquad** [comment]
The branch is at https://github.com/maxolasersquad/Castawesome/tree/python3

**Comment by TheSamsai** [comment]
Castawesome has now migrated to Python 3 and the first release with Python 3 is out.
